### ISSUE TITLE
NPM Module? 

### ISSUE THREAD

**Issue by kylevalenzuela** [maroslaw/rainyday.js#179]
Is there any chance to get this in an npm module for use ES6 imports. Currently, the npm link on the site goes to a pirate bay module. 

This would help in turning this script into a component. 

Thanks!

**Comment by mubaidr** [comment]
Sure, will definitely publish the newer version once it is fully tested.

**Comment by vFire** [comment]
Also hope the pause and resume function could be provided since this animation will degrade the performance e.g. when I add a login form upon the fullscreen rainyday, I hope when I focus the login form, the raining could be pause, that could largely improve the performance, so this could be more practical.

Thanks for this amazing script.

**Comment by mubaidr** [comment]
These options are already available but were not mentioned in the docs. I have updated the docs:
https://mubaidr.github.io/rainyday.js/

**Comment by mubaidr** [comment]
https://www.npmjs.com/package/rainyday.js
